#!/usr/bin/env python3
"""
Generate test_mode_image.h from a 160x100 PNG for TEST_IMAGE_MODE.

Accepted PNG formats: RGB, RGBA, palettized (all normalized to RGB).
Output format: Pico3D RGB4444 GBAR words (g<<12 | b<<8 | r).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

EXPECTED_WIDTH = 160
EXPECTED_HEIGHT = 100


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def rgb_to_gbar_word(r: int, g: int, b: int) -> int:
    r4 = (r >> 4) & 0x0F
    g4 = (g >> 4) & 0x0F
    b4 = (b >> 4) & 0x0F
    return (g4 << 12) | (b4 << 8) | r4


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate test mode image header.")
    parser.add_argument("--input", required=True, help="Input PNG path (must be 160x100)")
    parser.add_argument("--output", required=True, help="Output header path")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        fail(f"Input image not found: {input_path}")

    try:
        from PIL import Image
    except ImportError:
        fail(
            "Pillow is required to read PNG files. "
            "Install it with: python3 -m pip install pillow"
        )

    try:
        img = Image.open(input_path)
    except Exception as exc:
        fail(f"Failed to open PNG '{input_path}': {exc}")

    img = img.convert("RGB")
    width, height = img.size
    if width != EXPECTED_WIDTH or height != EXPECTED_HEIGHT:
        fail(
            f"Input image must be {EXPECTED_WIDTH}x{EXPECTED_HEIGHT}, "
            f"got {width}x{height}: {input_path}"
        )

    pixels = list(img.getdata())
    words = [rgb_to_gbar_word(r, g, b) for (r, g, b) in pixels]

    output_path.parent.mkdir(parents=True, exist_ok=True)

    header_lines = []
    header_lines.append("/* Auto-generated by tools/gen_test_mode_image.py — do not edit */")
    header_lines.append("#ifndef TEST_MODE_IMAGE_H")
    header_lines.append("#define TEST_MODE_IMAGE_H")
    header_lines.append("#include <stdint.h>")
    header_lines.append("")
    header_lines.append(f"#define TEST_MODE_IMAGE_WIDTH {EXPECTED_WIDTH}")
    header_lines.append(f"#define TEST_MODE_IMAGE_HEIGHT {EXPECTED_HEIGHT}")
    header_lines.append("")
    header_lines.append(
        f"static const uint16_t test_mode_image_rgb4444[{EXPECTED_WIDTH * EXPECTED_HEIGHT}] = {{"
    )
    for i in range(0, len(words), 16):
        chunk = words[i : i + 16]
        header_lines.append("    " + ", ".join(f"0x{w:04X}" for w in chunk) + ",")
    header_lines.append("};")
    header_lines.append("")
    header_lines.append("#endif /* TEST_MODE_IMAGE_H */")
    header_lines.append("")

    output_path.write_text("\n".join(header_lines), encoding="utf-8")
    print(f"Wrote {output_path} ({len(words)} pixels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
